## 1. Numpy import 하기

In [1]:
# numpy패키지를 np라는 별칭으로 가져와서 사용한다.
import numpy as np

In [20]:
import numpy as np

In [3]:
# import한 패키지의 별칭만 다르게 사용하면
# 모든 파이썬 패키지의 버전을 확인할수 있다.
print(np.__version__)

1.26.4


In [ ]:
# !는 리눅스 터미널 명령어를 사용할때 붙이는 기호
!pip list

## 2. ndarray 생성하기

In [9]:
# 파이썬의 리스트는 다양한 데이터 타입을 포함할 수 있다.
# numpy에서는 ndarray 생성시 데이터 타입을 하나로 통일하게 된다.
arr = np.array([1., 2, 3, 4], dtype=int)

In [10]:
arr

array([1, 2, 3, 4])

In [11]:
type(arr)

numpy.ndarray

In [13]:
arr0 = np.array([1.,2.,3.,4.])
print(arr0)
type(arr0)

[1. 2. 3. 4.]


numpy.ndarray

### 2-1. list로 부터 생성하기

In [21]:
import numpy as np

In [22]:
# 1차원 리스트
mylist1 = [1, 2, 3, 4]

In [23]:
# 2차원 리스트
mylist2 = [[1, 2, 3, 4],
           [5, 6, 7, 8]]

In [16]:
arr1 = np.array(mylist1)

In [17]:
arr2 = np.array(mylist2)

### 2-2. shape확인하기

In [25]:
# 4행으로 만들어진 array
arr1.shape

(4,)

In [28]:
print(arr1)

[1 2 3 4]


In [26]:
arr2.shape

(2, 4)

## 3. array에서의 data 타입

array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용

### 3-1. list에서의 data 타입

In [29]:
mylist = [1, 3.14, 'hello', '1234']

In [30]:
mylist

[1, 3.14, 'hello', '1234']

In [ ]:
mylist[1]

3.14

In [ ]:
mylist[2]

'hello'

### 3-2. array에서의 data 타입이 혼재된 경우

### int와 float 타입이 섞인 경우

In [31]:
arr = np.array([1, 2, 3, 3.14])

In [32]:
arr

array([1.  , 2.  , 3.  , 3.14])

### int와 float 타입이 섞인 경우, dtype을 지정한 경우

In [33]:
arr = np.array([1, 2, 3, 3.14], dtype=int)

In [34]:
arr

array([1, 2, 3, 3])

### int와 float, str 타입이 혼재된 경우

In [37]:
arr = np.array([1, 3.14, 'abc', '1234'])

In [38]:
arr

array(['1', '3.14', 'abc', '1234'], dtype='<U32')

In [39]:
arr[0] + arr[1]

'13.14'

### int와 str 타입이 혼재된 경우, int로 dtype을 지정한 경우

In [40]:
temp = '1234'
value = int(temp)
type(value)

int

In [45]:
arr = np.array([1, 3.14, '1234'], dtype=int)

In [44]:
arr

array([   1,    3, 1234])