In [1]:
import numpy as np

## 1. 행렬 - 덧셈

### 1-1. 덧셈

In [2]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [3]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [4]:
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [5]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [6]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [7]:
a + b

ValueError: ignored

### 1-2. Sum

In [8]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [10]:
np.sum(a, axis=0)

array([3, 5, 7])

In [11]:
np.sum(a, axis=1)

array([6, 9])

## 2. 행렬 - 뺄셈

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [ ]:
a - b

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [ ]:
a - b

## 3. 곱셈

일반 곱셈

In [12]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [13]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [14]:
a.shape, b.shape

((2, 3), (2, 3))

In [15]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

단순 곱셈과 dot product는 다릅니다. 이점 유의하세요!

In [16]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [17]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [18]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [19]:
a * b

ValueError: ignored

In [ ]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [ ]:
a.shape, b.shape

((3, 3), (3, 2))

In [ ]:
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [ ]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [ ]:
1*1 + 2*3 + 3*5

In [ ]:
1*2 + 2*4 + 3*6